### PR TITLE
Add JSON schema

### PR DESCRIPTION
**Pull request by EmilyGraceSeville7cf**

### CODE REVIEW

**Comment by EmilyGraceSeville7cf** [comment]
I will add this JSON schema to SchemaStore when this PR is accepted, like I've [done](https://github.com/SchemaStore/schemastore/pull/2901) with bashly.

**Comment by DannyBen** [comment]
I was waiting for your "all clear".
Should I consider all non-draft PRs ready to merge from now on?

**Comment by EmilyGraceSeville7cf** [comment]
> Should I consider all non-draft PRs ready to merge from now on?

Yes. :)

**Comment by EmilyGraceSeville7cf** [comment]
[Here](https://github.com/SchemaStore/schemastore/pull/3043) is a PR to SchemaStore.

**Comment by DannyBen** [comment]
Nice, thanks.

**Pull request merged**
